### ISSUE TITLE
redirection forbidden: http://www.ibm.com/... -> https://www.ibm.com/...

### ISSUE THREAD

**Issue by torreypayne** [suchowan/watson-api-client#7]
Hey guys, starting this morning, I've been getting a crazy bug from the client when I start my console/deploy. It seems that IBM redirects to HTTPS now, and the gem hasn't been updated accordingly (I'm guessing Congress may have something to do with this!).

ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:89:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'watson-api-client'. (Bundler::GemRequireError)
Gem Load Error is: redirection forbidden: http://www.ibm.com/watson/developercloud/doc/ -> https://www.ibm.com/watson/developercloud/doc/
Backtrace for gem load error is:
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:225:in `open_loop'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:717:in `open'
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/open-uri.rb:35:in `open'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watson-api-client-0.0.7/lib/watson-api-client.rb:35:in `retrieve_doc'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watson-api-client-0.0.7/lib/watson-api-client.rb:98:in `<class:WatsonAPIClient>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/watson-api-client-0.0.7/lib/watson-api-client.rb:7:in `<top (required)>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:86:in `require'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:81:in `each'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:81:in `block in require'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:70:in `each'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler/runtime.rb:70:in `require'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.12.1/lib/bundler.rb:102:in `require'

**Comment by miguelmyers8** [comment]
I am getting the same error. It works in development but not production.

**Comment by suchowan** [comment]
Do you get the same error even with the gem version 0.0.8?

**Comment by miguelmyers8** [comment]
Thanks for that, i just needed to update the gem.
